### ISSUE TITLE
MVP & Schema Review

### ISSUE THREAD

**Issue by vawhitehouse** [gretahayes19/AllTreks#1]
These look great overall! Just a few suggestions. 

## MVP
- [x] Hosting on Heroku date is outdated
- [x] Add days to dates
- [x] We only want 7 MVPs to start with so one of these should be moved to a bonus. I think the user profile would make the most sense for this. 
- Be thinking about where you will get trail/park data from. Seeded data? Api? 

## Schema
- [x] The sign up form asks for first name & last name rather than a username
- Would a photo belong to a hike or a review?

**Comment by gretahayes19** [comment]
Thanks Valerie! I fixed these issues.  As far as photos belonging to hikes vs reviews, AllTrails has tabs on each trail page for text reviews, and then a separate one for photos.  Oddly enough, it doesn't seem like they are connected to each other!
